# Copyright (c) 2021 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if (use_musl) {
  if (ohos_indep_compiler_enable) {
    musl_target = "//binarys/third_party/musl:musl_libs"
  } else {
    musl_target = "//third_party/musl:musl_libs"
  }
  musl_sysroot = get_label_info(musl_target, "target_out_dir")
  ## PEM Modify
    #0  import error at //build/config/ohos/musl.gni:21:3
        # 无法加载 "/home/zhuojw/a_git/ohos-mani-v2/third_party/musl/musl_config.gni"
    #1  imported by //build/config/ohos/config.gni:10:3
        # import("//build/config/ohos/musl.gni")
    #2  imported by //build/toolchain/ohos/ohos_toolchain.gni:6:1
        # import("//build/config/ohos/config.gni")
    #3  imported by //build/toolchain/ohos/BUILD.gn:5:1
        # import("//build/toolchain/ohos/ohos_toolchain.gni")
    #4  imported by //build/core/gn/BUILD.gn:36:3
        # group("make_all")
    # import("//third_party/musl/musl_config.gni")

    # Minimal musl config for build system test
    musl_use_prebuilt = false
    musl_build_dir = ""
    musl_is_legacy = false
}
